# Generated by Django 4.2 on 2024-03-12 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskflow', '0006_alter_project_name_alter_task_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('L', 'Low'), ('M', 'Medium'), ('H', 'High')], default='L', max_length=1, verbose_name='Task priority'),
        ),
    ]
