# Generated by Django 4.2 on 2024-03-11 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0004_alter_task_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.TextField(verbose_name='Project name'),
        ),
        migrations.AlterField(
            model_name='task',
            name='name',
            field=models.TextField(verbose_name='Task name'),
        ),
    ]
